name: Release Launcher

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  release-matrix:
    name: release amd64 binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64]
    steps:

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "${{  github.ref_name }}"
        release_name: Launcher ${{  github.ref_name }}

    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        ldflags: "-s -w"
        extra_files: LICENSE README.md
