name: Release Launcher

on:
  release:
    types: [created]

jobs:

  release-matrix:
    name: release amd64 binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64]
    steps:

    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.37
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        ldflags: "-s -w"
        project_path: "cmd"
        extra_files: LICENSE README.md
